[package]
name = "etheria-downloader"
version = "0.1.0"
authors = ["Alvin Null <supdrewin@outlook.com>"]
edition = "2021"
description = "Etheria Downloader powered by Rust"
repository = "https://github.com/supdrewin/etheria-downloader/"
license = "MIT"

[dependencies]
base16ct = { version = "0.2.0", features = ["std"] }
console = "0.15.10"
futures-util = "0.3.31"
indicatif = "0.17.9"
md-5 = "0.10.6"
num_cpus = "1.16.0"
reqwest = { version = "0.12.9", features = ["stream"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
tokio = { version = "1.42.0", features = ["full"] }
